version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: provenant-postgres
    environment:
      - POSTGRES_USER=provenant
      - POSTGRES_PASSWORD=provenant
      - POSTGRES_DB=store_master
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U provenant -d store_master"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: provenant-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    container_name: provenant-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: provenant/app:latest
    container_name: provenant-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://provenant:provenant@postgres:5432/store_master?schema=public
      - DATABASE_PREFIX=store_
      - JWT_SECRET=change-me
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    ports:
      - "3000:3000"
    # Enable graceful restarts if you want
    restart: unless-stopped
    # Because we run prisma migrate, we need the prisma dir present
    volumes:
      - ./prisma:/app/prisma:ro

volumes:
  pgdata:
  redisdata:
  rabbitmqdata:
